# CMake generated Testfile for 
# Source directory: /home/fenics/shared/VTK/Filters/HyperTree/Testing/Cxx
# Build directory: /home/fenics/shared/VTK-build/Filters/HyperTree/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2D "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2D" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2D.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisClipBox "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DAxisClipBox" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DAxisClipBox.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisClipBox PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisClipEllipse "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DAxisClipEllipse" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DAxisClipEllipse.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisClipEllipse PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisClipPlanes "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DAxisClipPlanes" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DAxisClipPlanes.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisClipPlanes PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisReflectionXCenter "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DAxisReflectionXCenter" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DAxisReflectionXCenter.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisReflectionXCenter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisReflectionXCenterMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DAxisReflectionXCenterMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DAxisReflectionXCenterMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisReflectionXCenterMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisReflectionYCenter "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DAxisReflectionYCenter" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DAxisReflectionYCenter.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisReflectionYCenter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisReflectionYCenterMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DAxisReflectionYCenterMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DAxisReflectionYCenterMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DAxisReflectionYCenterMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DIJK "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DIJK" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DIJK.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DIJK PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DCellCenters "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DCellCenters" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DCellCenters.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DCellCenters PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DCellCentersMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DCellCentersMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DCellCentersMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DCellCentersMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DContour "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DContour" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DContour.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DContourMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DContourMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DContourMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DContourMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DDepthLimiter "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DDepthLimiter" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DDepthLimiter.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DDepthLimiter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DDepthLimiterMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DDepthLimiterMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DDepthLimiterMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DDepthLimiterMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DInterfaceMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DInterfaceMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DInterfaceMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DInterfaceMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DMaterialIJK "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DMaterialIJK" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DMaterialIJK.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DMaterialIJK PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DThreshold "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DThreshold" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DThreshold.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DThreshold PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DThresholdMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DThresholdMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DThresholdMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DThresholdMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DVector "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DVector" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DVector.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DVector PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DVectorAxisReflectionXCenter "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DVectorAxisReflectionXCenter" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DVectorAxisReflectionXCenter.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DVectorAxisReflectionXCenter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DVectorAxisReflectionYCenter "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DVectorAxisReflectionYCenter" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DVectorAxisReflectionYCenter.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DVectorAxisReflectionYCenter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary3DContour "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary3DContour" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary3DContour.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary3DContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary3DGeometry "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary3DGeometry" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary3DGeometry.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary3DGeometry PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryClipPlanes "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinaryClipPlanes" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinaryClipPlanes.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryClipPlanes PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryEllipseMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinaryEllipseMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinaryEllipseMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryEllipseMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryHyperbolicParaboloidMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinaryHyperbolicParaboloidMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinaryHyperbolicParaboloidMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryHyperbolicParaboloidMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2D "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2D" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2D.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2DMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2DMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DMaterialBits "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2DMaterialBits" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2DMaterialBits.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DMaterialBits PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DFullMaterialBits "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2DFullMaterialBits" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2DFullMaterialBits.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DFullMaterialBits PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DBiMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2DBiMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2DBiMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DBiMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisClipBox "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisClipBox" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisClipBox.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisClipBox PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisClipCylinder "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisClipCylinder" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisClipCylinder.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisClipCylinder PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisClipPlanes "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisClipPlanes" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisClipPlanes.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisClipPlanes PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisCut "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisCut" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisCut.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisCut PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisCutMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisCutMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisCutMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisCutMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisReflectionXCenter "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisReflectionXCenter" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisReflectionXCenter.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisReflectionXCenter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisReflectionXCenterMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisReflectionXCenterMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisReflectionXCenterMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisReflectionXCenterMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisReflectionYZCenter "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisReflectionYZCenter" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisReflectionYZCenter.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisReflectionYZCenter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisReflectionYZCenterMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisReflectionYZCenterMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisReflectionYZCenterMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisReflectionYZCenterMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DCellCenters "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DCellCenters" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DCellCenters.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DCellCenters PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DCellCentersMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DCellCentersMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DCellCentersMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DCellCentersMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DContour "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DContour" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DContour.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DContourMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DContourMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DContourMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DContourMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DClip "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DClip" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DClip.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DClip PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DDualContour "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DDualContour" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DDualContour.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DDualContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DDualContourMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DDualContourMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DDualContourMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DDualContourMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometry "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DGeometry" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DGeometry.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometry PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DGeometryMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DGeometryMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryMaterialBits "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DGeometryMaterialBits" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DGeometryMaterialBits.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryMaterialBits PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryLargeMaterialBits "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DGeometryLargeMaterialBits" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DGeometryLargeMaterialBits.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryLargeMaterialBits PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DPlaneCutter "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DPlaneCutter" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DPlaneCutter.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DPlaneCutter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DPlaneCutterDual "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DPlaneCutterDual" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DPlaneCutterDual.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DPlaneCutterDual PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DThreshold "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DThreshold" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DThreshold.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DThreshold PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DThresholdMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DThresholdMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DThresholdMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DThresholdMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DUnstructured "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DUnstructured" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DUnstructured.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DUnstructured PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DUnstructuredMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DUnstructuredMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DUnstructuredMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DUnstructuredMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernaryHyperbola "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernaryHyperbola" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernaryHyperbola.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernaryHyperbola PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernarySphereMaterial "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernarySphereMaterial" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernarySphereMaterial.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernarySphereMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
add_test(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernarySphereMaterialReflections "/home/fenics/shared/VTK-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernarySphereMaterialReflections" "-D" "/home/fenics/shared/VTK-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernarySphereMaterialReflections.png")
set_tests_properties(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernarySphereMaterialReflections PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkFiltersHyperTree" SKIP_RETURN_CODE "125")
