# CMake generated Testfile for 
# Source directory: /home/fenics/shared/VTK/Rendering/VolumeOpenGL2/Testing/Cxx
# Build directory: /home/fenics/shared/VTK-build/VTK-Release-build/Rendering/VolumeOpenGL2/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastCellData "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastCellData" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastCellData.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastCellData PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeeling "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastDepthPeeling" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastDepthPeeling.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingBoxWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastDepthPeelingBoxWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastDepthPeelingBoxWidget.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingBoxWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingBlendModes "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastDepthPeelingBlendModes" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastDepthPeelingBlendModes.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingBlendModes PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingClip "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastDepthPeelingClip" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastDepthPeelingClip.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingClip PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingOpaque "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastDepthPeelingOpaque" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastDepthPeelingOpaque.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingOpaque PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingTransVol "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastDepthPeelingTransVol" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastDepthPeelingTransVol.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingTransVol PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingTransparentPolyData "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastDepthPeelingTransparentPolyData" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastDepthPeelingTransparentPolyData.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastDepthPeelingTransparentPolyData PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastIsosurface "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastIsosurface" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastIsosurface.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastIsosurface PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastJittering "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastJittering" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastJittering.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastJittering PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastTextureStreaming "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastTextureStreaming" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastTextureStreaming.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastTextureStreaming PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastTextureStreamingMask "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastTextureStreamingMask" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastTextureStreamingMask.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastTextureStreamingMask PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastToggleJittering "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastToggleJittering" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastToggleJittering.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastToggleJittering PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastUserShader "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastUserShader" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastUserShader.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastUserShader PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
add_test(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastUserShader2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeOpenGL2CxxTests" "TestGPURayCastUserShader2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Rendering/VolumeOpenGL2/Testing/Data/Baseline/TestGPURayCastUserShader2.png")
set_tests_properties(vtkRenderingVolumeOpenGL2Cxx-TestGPURayCastUserShader2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkRenderingVolumeOpenGL2" SKIP_RETURN_CODE "125")
