set(vtkChartsCore_HEADERS_LOADED 1)
set(vtkChartsCore_HEADERS "vtkAxis;vtkAxisExtended;vtkCategoryLegend;vtkChart;vtkChartBox;vtkChartHistogram2D;vtkChartLegend;vtkChartMatrix;vtkChartParallelCoordinates;vtkChartPie;vtkChartXY;vtkChartXYZ;vtkColorLegend;vtkColorTransferControlPointsItem;vtkColorTransferFunctionItem;vtkCompositeControlPointsItem;vtkCompositeTransferFunctionItem;vtkContextArea;vtkContextPolygon;vtkControlPointsItem;vtkInteractiveArea;vtkLookupTableItem;vtkPiecewiseControlPointsItem;vtkPiecewiseFunctionItem;vtkPiecewisePointHandleItem;vtkPlot;vtkPlot3D;vtkPlotArea;vtkPlotBag;vtkPlotBar;vtkPlotBox;vtkPlotFunctionalBag;vtkPlotGrid;vtkPlotHistogram2D;vtkPlotLine;vtkPlotLine3D;vtkPlotParallelCoordinates;vtkPlotPie;vtkPlotPoints;vtkPlotPoints3D;vtkPlotStacked;vtkPlotSurface;vtkScalarsToColorsItem;vtkScatterPlotMatrix")

foreach(header ${vtkChartsCore_HEADERS})
  set(vtkChartsCore_HEADER_${header}_EXISTS 1)
endforeach()
