// Defined variables

#define MYOSIM_VERSION 2.5

// Check string
#define MYOSIM_CHECK_STRING "//MYOSIM"

// TEMPERATURE
#define K_BOLTZMANN 1.38e-23

// Other
#define PI 3.14159
#define VERY_HIGH_RATE 10000.0
#define VERY_LOW_RATE 1e-3
#define MAX_PATHWAYS 4
#define MAX_RATE_FUNCTION_PARAMETERS 15

#define MAX_STRING_LENGTH 1000


/*
#define BASE_KINETICS_DUMP_FILE_STRING "kinetics"
#define BASE_PARAMETERS_FILE_STRING "parameters"
*/

#define DEFAULT_INSTRUCTION_FILE_STRING "instruction_file.txt"
#define DEFAULT_OUTPUT_DIRECTORY_STRING "MyoSim_output"

#define MYOSIM_TAG "//MYOSIM_HEADER"
#define MUSCLE_TAG "//MUSCLE"
#define DISTRIBUTIONS_TAG "//DISTRIBUTIONS"
#define KINETICS_TAG "//KINETICS"
#define MYOSIN_ISOFORM_TAG "//MYOSIN_ISOFORMS"
#define PROTOCOL_TAG "//PROTOCOL"
#define FIXED_TAG "//FIXED_PARAMETERS"
#define ADJUSTABLE_TAG "//ADJUSTABLE_PARAMETERS"

#define POPULATION_DUMP_FILE_STRING "cb_populations"
#define HS_STATUS_FILE_STRING "status"
#define PARAMETERS_FILE_STRING "parameters"

#define ISOTONIC_ZERO_FORCE_CHECK -1

#define POPULATION_REL_TOLERANCE 0.0
#define POPULATION_ABS_TOLERANCE 1.0e-6
#define ISOTONIC_FORCE_HSL_TOLERANCE 1e-6
#define ISOTONIC_FORCE_INITIAL_ADJUSTMENT 300.0

#define FORCE_BALANCE_RESIDUAL 1e-3
#define FORCE_BALANCE_MAX_ITERATIONS 100

#define DEFAULT_HS_SLACK_LENGTH -99.0

#define NO_OF_CONDITION_PARAMETERS 6

#define M_MAX_NO_OF_ISOFORMS 3

#define HS_DF_ACTIVATED_TERMS 3

#define MAX_NO_OF_HALF_SARCOMERES 100
#define MAX_NO_OF_CONDITIONS 100
#define MAX_NO_OF_SCALING_FACTORS 10

#define MAX_NO_OF_TRANSITIONS 50

#define DEFAULT_DELTA_PARAMETER_VALUE -99.0

#define NO_OF_HS_TIMERS 8
#define TIMER_SET_N 0
#define TIMER_EVOLVE_CB_POPULATIONS 1
#define TIMER_SHIFT_CB_DISTRIBUTIONS 2
#define TIMER_HS_LENGTH_FOR_FORCE 3
#define TIMER_FORCES_AND_POPS 4
#define TIMER_GSL_ODEIV 5
#define TIMER_DERIVS 6
#define TIMER_JACOB 7
