# CMake generated Testfile for 
# Source directory: /home/fenics/shared/VTK/Interaction/Widgets/Testing/Cxx
# Build directory: /home/fenics/shared/VTK-build/VTK-Release-build/Interaction/Widgets/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vtkInteractionWidgetsCxx-BoxWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "BoxWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/BoxWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-BoxWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-BoxWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "BoxWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/BoxWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-BoxWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-ImagePlaneWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "ImagePlaneWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/ImagePlaneWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-ImagePlaneWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TerrainPolylineEditor "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TerrainPolylineEditor" "-ProjectionMode" "2" "-HeightOffset" "100" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TerrainPolylineEditor.png")
set_tests_properties(vtkInteractionWidgetsCxx-TerrainPolylineEditor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125" TIMEOUT "90")
add_test(vtkInteractionWidgetsCxx-TestAffineWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestAffineWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestAffineWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestAffineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestAngleWidget2D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestAngleWidget2D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestAngleWidget2D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestAngleWidget2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestAngleWidget3D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestAngleWidget3D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestAngleWidget3D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestAngleWidget3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestBalloonWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestBalloonWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestBalloonWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestBalloonWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestBiDimensionalWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestBiDimensionalWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestBiDimensionalWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestBiDimensionalWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestBorderWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestBorderWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestBorderWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestBorderWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestBrokenLineWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestBrokenLineWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestBrokenLineWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestBrokenLineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestCameraWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCameraWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCameraWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestCameraWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestCaptionWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCaptionWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCaptionWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestCaptionWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestCellCentersPointPlacer "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCellCentersPointPlacer" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCellCentersPointPlacer.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestCellCentersPointPlacer PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestCenteredSliderWidget2D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCenteredSliderWidget2D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCenteredSliderWidget2D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestCenteredSliderWidget2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestCheckerboardWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCheckerboardWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCheckerboardWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestCheckerboardWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestConstrainedHandleWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestConstrainedHandleWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestConstrainedHandleWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestConstrainedHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestContourWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestContourWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestContourWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestContourWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestDijkstraImageGeodesicPath "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestDijkstraImageGeodesicPath" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestDijkstraImageGeodesicPath.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestDijkstraImageGeodesicPath PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestDistanceWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestDistanceWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestDistanceWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestDistanceWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestDistanceWidget3D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestDistanceWidget3D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestDistanceWidget3D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestDistanceWidget3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestFinitePlaneWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestFinitePlaneWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestFinitePlaneWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestFinitePlaneWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestFixedSizeHandleRepresentation3D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestFixedSizeHandleRepresentation3D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestFixedSizeHandleRepresentation3D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestFixedSizeHandleRepresentation3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestFocalPlaneContour "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestFocalPlaneContour" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestFocalPlaneContour.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestFocalPlaneContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestHandleWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestHandleWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestHandleWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestHandleWidget2D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestHandleWidget2D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestHandleWidget2D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestHandleWidget2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImageActorContourWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImageActorContourWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImageActorContourWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImageActorContourWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImplicitCylinderWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitCylinderWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitCylinderWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImplicitCylinderWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImplicitCylinderWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitCylinderWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitCylinderWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImplicitCylinderWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2LockNormalToCamera "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget2LockNormalToCamera" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget2LockNormalToCamera.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2LockNormalToCamera PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2b "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget2b" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget2b.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2b PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget3 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget3" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget3.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget3 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestLogoWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLogoWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLogoWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestLogoWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestLogoWidgetAlphaBlending "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLogoWidgetAlphaBlending" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLogoWidgetAlphaBlending.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestLogoWidgetAlphaBlending PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestLogoWidgetDepthPeeling "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLogoWidgetDepthPeeling" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLogoWidgetDepthPeeling.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestLogoWidgetDepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestMeasurementCubeHandleRepresentation3D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestMeasurementCubeHandleRepresentation3D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestMeasurementCubeHandleRepresentation3D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestMeasurementCubeHandleRepresentation3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestMultipleViewports "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestMultipleViewports" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestMultipleViewports.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestMultipleViewports PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestOrientationMarkerWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestOrientationMarkerWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestOrientationMarkerWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestOrientationMarkerWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestOrientationMarkerWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestOrientationMarkerWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestOrientationMarkerWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestOrientationMarkerWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestOrthoPlanes "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestOrthoPlanes" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestOrthoPlanes.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestOrthoPlanes PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestParallelopipedWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestParallelopipedWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestParallelopipedWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestParallelopipedWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPickingManagerSeedWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPickingManagerSeedWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPickingManagerSeedWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPickingManagerSeedWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125" TIMEOUT "60")
add_test(vtkInteractionWidgetsCxx-TestPickingManagerSeedWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPickingManagerSeedWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPickingManagerSeedWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPickingManagerSeedWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPlaybackWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPlaybackWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPlaybackWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPlaybackWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPointHandleRepresentation3D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPointHandleRepresentation3D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPointHandleRepresentation3D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPointHandleRepresentation3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPolylineWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolylineWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPolylineWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPolylineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestProgrammaticPlacement "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestProgrammaticPlacement" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestProgrammaticPlacement.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestProgrammaticPlacement PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestProgressBarWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestProgressBarWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestProgressBarWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestProgressBarWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestProp3DButtonRepresentation "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestProp3DButtonRepresentation" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-TestProp3DButtonRepresentation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestRectilinearWipeWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestRectilinearWipeWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestRectilinearWipeWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestRectilinearWipeWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestResliceCursorWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestResliceCursorWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestResliceCursorWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestResliceCursorWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestResliceCursorWidget3 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestResliceCursorWidget3" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestResliceCursorWidget3.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestResliceCursorWidget3 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestScalarBarWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestScalarBarWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestScalarBarWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestScalarBarWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSeedWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSeedWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSeedWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSeedWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSeedWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSeedWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSeedWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSeedWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSeedWidgetNonUniformRepresentations "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSeedWidgetNonUniformRepresentations" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSeedWidgetNonUniformRepresentations.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSeedWidgetNonUniformRepresentations PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSliderWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSliderWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSliderWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSliderWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSliderWidget2D "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSliderWidget2D" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSliderWidget2D.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSliderWidget2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSliderWidgetMultipleViewports "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSliderWidgetMultipleViewports" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSliderWidgetMultipleViewports.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSliderWidgetMultipleViewports PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSphereWidget2CenterCursor "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSphereWidget2CenterCursor" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSphereWidget2CenterCursor.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSphereWidget2CenterCursor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSphereWidgetZoomInOut "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSphereWidgetZoomInOut" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSphereWidgetZoomInOut.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSphereWidgetZoomInOut PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSplineWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSplineWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSplineWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSplineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestTextWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestTextWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestTextWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestTextWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkAngleRepresentation2DTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkAngleRepresentation2DTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkAngleRepresentation2DTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkAngleRepresentation3DTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkAngleRepresentation3DTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkAngleRepresentation3DTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkAngleWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkAngleWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkAngleWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkBalloonRepresentationTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBalloonRepresentationTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkBalloonRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkBalloonWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBalloonWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkBalloonWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkBiDimensionalRepresentation2DTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBiDimensionalRepresentation2DTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkBiDimensionalRepresentation2DTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkBiDimensionalWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBiDimensionalWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkBiDimensionalWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkBorderWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBorderWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkBorderWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkCaptionRepresentationTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkCaptionRepresentationTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkCaptionRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkCaptionWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkCaptionWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkCaptionWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkConstrainedPointHandleRepresentationTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkConstrainedPointHandleRepresentationTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkConstrainedPointHandleRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkHoverWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkHoverWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkHoverWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkLineRepresentationTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkLineRepresentationTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkLineRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkLineWidget2Test1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkLineWidget2Test1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkLineWidget2Test1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkPolyLineRepresentationTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkPolyLineRepresentationTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkPolyLineRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkPolyLineWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkPolyLineWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkPolyLineWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkSeedRepresentationTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkSeedRepresentationTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkSeedRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkSeedWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkSeedWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkSeedWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkSplineRepresentationTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkSplineRepresentationTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkSplineRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkSplineWidget2Test1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkSplineWidget2Test1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkSplineWidget2Test1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkTextRepresentationTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkTextRepresentationTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkTextRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-vtkTextWidgetTest1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkTextWidgetTest1" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-vtkTextWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestButtonWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestButtonWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestButtonWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestButtonWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestButtonWidgetMultipleViewports "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestButtonWidgetMultipleViewports" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestButtonWidgetMultipleViewports.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestButtonWidgetMultipleViewports PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestDijkstraGraphGeodesicPath "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestDijkstraGraphGeodesicPath" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestDijkstraGraphGeodesicPath.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestDijkstraGraphGeodesicPath PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestLineWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLineWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLineWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestLineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestLineWidget2 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLineWidget2" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLineWidget2.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestLineWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestOrientedGlyphContour "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestOrientedGlyphContour" "--PlaybackFile" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Input/TestOrientedGlyphContourEventLog.txt" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestOrientedGlyphContour.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestOrientedGlyphContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPlaneWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPlaneWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPlaneWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPlaneWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPointWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPointWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPointWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPointWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPolyPlane "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolyPlane" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkInteractionWidgetsCxx-TestPolyPlane PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPolygonalHandleRepresentations "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolygonalHandleRepresentations" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPolygonalHandleRepresentations.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPolygonalHandleRepresentations PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPolygonalRepresentationHandleWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolygonalRepresentationHandleWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPolygonalRepresentationHandleWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPolygonalRepresentationHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPolygonalSurfaceConstrainedDistanceWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolygonalSurfaceConstrainedDistanceWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPolygonalSurfaceConstrainedDistanceWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPolygonalSurfaceConstrainedDistanceWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestSphereHandleWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSphereHandleWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSphereHandleWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSphereHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" RUN_SERIAL "ON" SKIP_RETURN_CODE "125" TIMEOUT "300")
add_test(vtkInteractionWidgetsCxx-TestSurfaceConstrainedHandleWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSurfaceConstrainedHandleWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSurfaceConstrainedHandleWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestSurfaceConstrainedHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestTensorProbeWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestTensorProbeWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestTensorProbeWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestTensorProbeWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestImageTracerWidget "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImageTracerWidget" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImageTracerWidget.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestImageTracerWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
add_test(vtkInteractionWidgetsCxx-TestPickingManagerWidgets "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPickingManagerWidgets" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPickingManagerWidgets.png")
set_tests_properties(vtkInteractionWidgetsCxx-TestPickingManagerWidgets PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkInteractionWidgets" SKIP_RETURN_CODE "125")
