# CMake generated Testfile for 
# Source directory: /home/fenics/shared/VTK/IO/Import/Testing/Cxx
# Build directory: /home/fenics/shared/VTK-build/VTK-Release-build/IO/Import/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vtkIOImportCxx-OBJImporter-TwoTrianglesWithNegativeIndices "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestOBJImporter" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TwoTrianglesWithNegativeIndices.obj" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TwoTrianglesWithNegativeIndices.mtl" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/noise.png" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/OBJImporter-TwoTrianglesWithNegativeIndices.png")
set_tests_properties(vtkIOImportCxx-OBJImporter-TwoTrianglesWithNegativeIndices PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-OBJImport-SolidAndTextured "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestOBJImporter" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/cube-scene.obj" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/cube-scene.mtl" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/noise.png" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/OBJImport-SolidAndTextured.png")
set_tests_properties(vtkIOImportCxx-OBJImport-SolidAndTextured PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-OBJImport-MixedOrder1 "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestOBJImporter" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/boxes_2.obj" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/boxes_2.obj.mtl" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/flare.jpg" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/OBJImport-MixedOrder1.png")
set_tests_properties(vtkIOImportCxx-OBJImport-MixedOrder1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-OBJImport-NoMTL "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestOBJImporter" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/boxes_3_no_mtl.obj" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/boxes_2.obj.mtl" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/flare.jpg" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/OBJImport-NoMTL.png")
set_tests_properties(vtkIOImportCxx-OBJImport-NoMTL PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-OBJImport-MTLwithoutTextureFile "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestOBJImporter" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/boxes_4_mtl_no_texture.obj" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/boxes_4_mtl_no_texture.obj.mtl" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/OBJImport-MTLwithoutTextureFile.png")
set_tests_properties(vtkIOImportCxx-OBJImport-MTLwithoutTextureFile PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-TestOBJImporter-DuplicateMaps "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestOBJImporter" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TestOBJImporter.obj" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TestOBJImporter.mtl" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TestOBJImporter.png" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/TestOBJImporter-DuplicateMaps.png")
set_tests_properties(vtkIOImportCxx-TestOBJImporter-DuplicateMaps PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-TestOBJImporter-SharedMtl "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestOBJImporter" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TestOBJImporter-SharedMtl.obj" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TestOBJImporter-SharedMtl.mtl" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/TestOBJImporter-SharedMtl.png")
set_tests_properties(vtkIOImportCxx-TestOBJImporter-SharedMtl PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-TestOBJImporter-VtNoIndices "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestOBJImporter" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TestOBJImporter-VtNoIndices.obj" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TestOBJImporter-VtNoIndices.mtl" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Input/TestOBJImporter-VtNoIndices.png" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/TestOBJImporter-VtNoIndices.png")
set_tests_properties(vtkIOImportCxx-TestOBJImporter-VtNoIndices PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-TestVRMLImporter "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestVRMLImporter" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary")
set_tests_properties(vtkIOImportCxx-TestVRMLImporter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
add_test(vtkIOImportCxx-TestVRMLNormals "/home/fenics/shared/VTK-build/VTK-Release-build/bin/vtkIOImportCxxTests" "TestVRMLNormals" "-D" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/fenics/shared/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/fenics/shared/VTK-build/VTK-Release-build/ExternalData/IO/Import/Testing/Data/Baseline/TestVRMLNormals.png")
set_tests_properties(vtkIOImportCxx-TestVRMLNormals PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: ;instance(s)? still around" LABELS "vtkIOImport" SKIP_RETURN_CODE "125")
