set(vtkFiltersModeling_HEADERS_LOADED 1)
set(vtkFiltersModeling_HEADERS "vtkAdaptiveSubdivisionFilter;vtkBandedPolyDataContourFilter;vtkButterflySubdivisionFilter;vtkContourLoopExtraction;vtkCookieCutter;vtkDijkstraGraphGeodesicPath;vtkDijkstraImageGeodesicPath;vtkFitToHeightMapFilter;vtkFillHolesFilter;vtkGeodesicPath;vtkGraphGeodesicPath;vtkLinearExtrusionFilter;vtkLinearSubdivisionFilter;vtkLoopSubdivisionFilter;vtkOutlineFilter;vtkPolyDataPointSampler;vtkProjectedTexture;vtkQuadRotationalExtrusionFilter;vtkRibbonFilter;vtkRotationalExtrusionFilter;vtkRuledSurfaceFilter;vtkSectorSource;vtkSelectEnclosedPoints;vtkSelectPolyData;vtkSpherePuzzleArrows;vtkSpherePuzzle;vtkSubdivideTetra;vtkTrimmedExtrusionFilter;vtkVolumeOfRevolutionFilter")

foreach(header ${vtkFiltersModeling_HEADERS})
  set(vtkFiltersModeling_HEADER_${header}_EXISTS 1)
endforeach()
